Prudential data set. This is the newest Kaggle competition figuring out the person's probability of purchasing life insurance. Data sets dependent on person's age, height, weight, and employment. Numerous columns I have to clean up additional data as there are 128 columns on both the test and training set. Have to split with the applicant age height weight BMI against history

In [4]:
# Imports
import numpy as np
import pandas as pd

# Load the data in
testcsv = pd.read_csv("C:\\Users\\rs\\Desktop\\prudential\\test\\test.csv")
# Take a look
testcsv.head()

,Id,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,...,Medical_Keyword_39,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48
0,1,1,D3,26,0.487179,2,3,1,0.611940,0.781818,...,0,0,0,0,0,0,0,0,0,0
1,3,1,A2,26,0.076923,2,3,1,0.626866,0.727273,...,0,0,0,0,0,0,0,0,0,0
2,4,1,D3,26,0.144667,2,3,1,0.582090,0.709091,...,0,0,0,0,0,0,0,0,0,0
3,9,1,A1,26,0.151709,2,1,1,0.522388,0.654545,...,0,0,0,0,0,0,0,0,1,1
4,12,1,A1,26,0.076923,2,3,1,0.298507,0.672727,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# Imports
import numpy as np
import pandas as pd

# Load the data in
traincsv = pd.read_csv("C:\\Users\\rs\\Desktop\\prudential\\trainset\\train.csv")
# Take a look
traincsv.head()

,Id,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,...,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48,Response
0,2,1,D3,10,0.076923,2,1,1,0.641791,0.581818,...,0,0,0,0,0,0,0,0,0,8
1,5,1,A1,26,0.076923,2,3,1,0.059701,0.600000,...,0,0,0,0,0,0,0,0,0,4
2,6,1,E1,26,0.076923,2,3,1,0.029851,0.745455,...,0,0,0,0,0,0,0,0,0,8
3,7,1,D4,10,0.487179,2,3,1,0.164179,0.672727,...,0,0,0,0,0,0,0,0,0,8
4,8,1,D2,26,0.230769,2,3,1,0.417910,0.654545,...,0,0,0,0,0,0,0,0,0,8

In [10]:
files = [testcsv, traincsv]
df = pd.concat(files)
print df

            BMI  Employment_Info_1  Employment_Info_2  Employment_Info_3  \
0      0.472262           0.150000                  3                  1
1      0.484984           0.000000                  1                  3
2      0.519103           0.143000                  9                  1
3      0.486962           0.210000                  9                  1
4      0.428718           0.085000                  9                  1
5      0.379754           0.075000                  9                  1
6      0.373628           0.140000                  9                  1
7      0.388655           0.025000                  9                  1
8      0.446361           0.035000                  9                  1
9      0.443418           0.060000                  9                  1
10     0.362274           0.300000                  1                  3
11     0.314304           0.040000                 12                  1
12     0.393349           0.020000                  9                  1
13     0.297097           0.052008                  9                  1
14     0.401656           0.030000                  9                  1
15     0.408129           0.100000                  9                  1
16     0.367372           0.000000                  1                  3
17     0.385344           0.090000                  9                  1
18     0.345771           0.200000                  9                  1
19     0.488220           0.062000                  9                  1
20     0.455286           0.040000                  1                  3
21     0.418301           0.045000                 14                  1
22     0.354708           0.600000                  9                  1
23     0.344810           0.035000                  9                  1
24     0.444667           0.100000                 14                  1
25     0.551286           0.075000                  1                  3
26     0.391202           0.145000                  1                  3
27     0.339455           0.150000                 14                  1
28     0.631095           0.025000                 12                  1
29     0.325490           0.020000                  1                  3
...         ...                ...                ...                ...
59351  0.491491           0.070000                 12                  1
59352  0.488220           0.020000                 12                  1
59353  0.539563           0.080000                  9                  1
59354  0.494104           0.050000                 12                  1
59355  0.547451           0.058000                  9                  1
59356  0.618050           0.040000                  9                  1
59357  0.491491           0.125000                  9                  1
59358  0.586182           0.090000                  9                  1
59359  0.603660           0.060000                 14                  1
59360  0.258890           0.080000                  9                  1
59361  0.411703           0.250000                  3                  1
59362  0.491491           0.054000                  9                  1
59363  0.464570           0.000000                  1                  3
59364  0.261651           0.050000                 12                  1
59365  0.458023           0.045000                  9                  1
59366  0.443418           0.058000                 14                  1
59367  0.661270           0.160000                  9                  1
59368  0.464047           0.090000                  9                  1
59369  0.693246           0.092000                  1                  3
59370  0.477625           0.065000                  9                  1
59371  0.558626           0.065000                 12                  1
59372  0.438076           0.200000                 14                  1
59373  0.332885           0.032000                  9                  1
59374  0.484658           0.059000                  9                  1
59375  0.494827           0.045000                  9                  1
59376  0.519103           0.020000                  1                  3
59377  0.551119           0.100000                  9                  1
59378  0.360969           0.035000                  9                  1
59379  0.462452           0.038000                  9                  1
59380  0.539563           0.123000                  9                  1

       Employment_Info_4  Employment_Info_5  Employment_Info_6  Family_Hist_1  \
0                0.00000                  2             0.5000              3
1                0.07000                  2             0.2000              2
2                0.00000                  2             0.4500              3
3                0.00000                  2             1.0000              2
4                0.00000                  2             0.2000              2
5                0.00000                  2             0.4000              3
6                0.00000                  2             1.0000              2
7                0.00000                  2             0.0000              2
8                0.00000                  2                NaN              3
9                0.00000                  2             1.0000              3
10               0.03000                  2             1.0000              3
11               0.00000                  3             0.6000              3
12               0.00000                  2             1.0000              3
13               0.00000                  2                NaN              2
14               0.00000                  2             0.0000              2
15               0.00000                  2             1.0000              2
16               0.01600                  2             0.0013              3
17               0.00300                  2             0.0600              3
18               0.00000                  2             0.0500              3
19               0.00000                  2             0.1500              3
20               0.00000                  2                NaN              3
21               0.00000                  2             0.0250              2
22               0.00000                  2             1.0000              3
23               0.00000                  3             0.1200              3
24               0.00000                  2             0.0000              3
25               0.00000                  3             0.5000              2
26               0.00000                  2             0.3500              3
27               0.00000                  2             0.5000              3
28               0.00000                  2             1.0000              3
29               0.00000                  3             0.1000              3
...                  ...                ...                ...            ...
59351            0.00000                  2             0.0700              2
59352            0.00000                  3             0.1000              3
59353            0.00000                  2             0.0000              3
59354            0.02000                  2             0.2500              3
59355            0.00000                  2             0.2250              2
59356            0.00000                  3                NaN              3
59357            0.02500                  2             1.0000              2
59358                NaN                  2             0.0050              3
59359            0.00750                  2             0.2250              3
59360            0.00000                  2             0.1500              3
59361            0.00000                  2             0.9000              2
59362            0.00000                  2             0.0250              3
59363            0.00000                  3             0.0000              3
59364            0.00000                  2             0.0000              3
59365            0.00000                  3             0.2000              2
59366            0.00000                  2             0.3000              2
59367            0.00000                  2             0.0000              2
59368            0.00000                  2             0.2000              3
59369                NaN                  2             0.1600              3
59370            0.00000                  2             0.0500              2
59371            0.00000                  2                NaN              2
59372            0.00000                  2             0.3000              3
59373            0.00000                  3                NaN              3
59374            0.00000                  2             0.0200              3
59375            0.00000                  2             0.0450              2
59376            0.00000                  3             0.0250              3
59377            0.00001                  2             0.3500              3
59378            0.00000                  2                NaN              3
59379                NaN                  3                NaN              2
59380                NaN                  2             0.3000              2

       Family_Hist_2  Family_Hist_3    ...     Medical_Keyword_9  \
0                NaN       0.627451    ...                     0
1                NaN       0.529412    ...                     0
2           0.666667            NaN    ...                     0
3                NaN       0.686275    ...                     0
4           0.449275            NaN    ...                     0
5                NaN       0.647059    ...                     0
6           0.449275            NaN    ...                     0
7           0.391304            NaN    ...                     0
8                NaN       0.656863    ...                     0
9           0.637681            NaN    ...                     0
10          0.434783            NaN    ...                     0
11               NaN       0.372549    ...                     0
12          0.391304            NaN    ...                     0
13          0.376812            NaN    ...                     0
14          0.275362            NaN    ...                     0
15          0.681159            NaN    ...                     0
16               NaN       0.254902    ...                     0
17          0.347826            NaN    ...                     0
18          0.333333            NaN    ...                     0
19               NaN       0.500000    ...                     0
20               NaN       0.284314    ...                     0
21          0.362319            NaN    ...                     0
22          0.536232            NaN    ...                     0
23          0.449275            NaN    ...                     0
24          0.782609            NaN    ...                     0
25               NaN       0.431373    ...                     0
26               NaN       0.637255    ...                     0
27          0.637681            NaN    ...                     0
28               NaN       0.568627    ...                     0
29          0.434783            NaN    ...                     0
...              ...            ...    ...                   ...
59351            NaN       0.254902    ...                     0
59352            NaN            NaN    ...                     0
59353       0.275362            NaN    ...                     0
59354       0.608696            NaN    ...                     0
59355       0.405797            NaN    ...                     0
59356            NaN       0.598039    ...                     0
59357            NaN       0.617647    ...                     0
59358       0.275362            NaN    ...                     0
59359            NaN       0.568627    ...                     0
59360       0.304348            NaN    ...                     0
59361       0.478261            NaN    ...                     0
59362       0.449275            NaN    ...                     0
59363            NaN       0.519608    ...                     0
59364            NaN       0.598039    ...                     0
59365            NaN       0.578431    ...                     0
59366            NaN       0.480392    ...                     0
59367            NaN       0.568627    ...                     0
59368            NaN       0.568627    ...                     0
59369            NaN       0.627451    ...                     0
59370            NaN       0.078431    ...                     0
59371            NaN       0.519608    ...                     0
59372       0.681159            NaN    ...                     0
59373       0.275362            NaN    ...                     0
59374       0.405797            NaN    ...                     0
59375            NaN            NaN    ...                     0
59376       0.217391            NaN    ...                     0
59377       0.565217            NaN    ...                     0
59378       0.173913            NaN    ...                     0
59379            NaN       0.372549    ...                     0
59380            NaN       0.401961    ...                     0

       Product_Info_1  Product_Info_2  Product_Info_3  Product_Info_4  \
0                   1              D3              26        0.487179
1                   1              A2              26        0.076923
2                   1              D3              26        0.144667
3                   1              A1              26        0.151709
4                   1              A1              26        0.076923
5                   1              D3              26        0.230769
6                   1              A3              26        1.000000
7                   1              D4              26        0.256410
8                   1              D3              26        0.076923
9                   1              A3              26        0.076923
10                  1              D4              26        1.000000
11                  1              D1              29        0.384615
12                  1              E1              26        0.230769
13                  1              D1              26        0.179487
14                  1              D1              26        0.076923
15                  1              E1              26        0.158974
16                  1              A2              26        0.076923
17                  1              D4              26        0.230769
18                  1              D3              26        0.487179
19                  1              A8              26        0.076923
20                  1              D4              26        0.487179
21                  1              D4              26        0.461538
22                  1              D3              26        1.000000
23                  1              D3              10        0.230769
24                  1              D3              26        0.282051
25                  1              D2              29        0.487179
26                  1              D3              26        0.435897
27                  1              A6              26        0.230769
28                  1              A8              26        0.230769
29                  2              D2              15        0.076923
...               ...             ...             ...             ...
59351               1              A7              26        0.000000
59352               1              D2              10        0.230769
59353               1              D4              26        0.589744
59354               1              D2              26        0.487179
59355               1              D3              26        0.230769
59356               1              D3              10        0.076923
59357               1              D3              26        1.000000
59358               1              D4              26        0.282051
59359               1              D3              26        0.230769
59360               1              D4              26        1.000000
59361               1              A1              26        0.230769
59362               1              D4              26        0.230769
59363               1              D2               4        0.076923
59364               1              D2              26        0.076923
59365               1              D1              29        0.076923
59366               1              D1              26        0.282051
59367               1              E1              26        0.179487
59368               1              D4              26        0.230769
59369               1              D1              26        0.179487
59370               1              D3              26        0.230769
59371               1              D3              26        0.487179
59372               1              D3              26        0.487179
59373               2              D4              29        0.487179
59374               1              D4              26        0.307692
59375               1              C1              26        0.076923
59376               1              D1              10        0.230769
59377               1              D3              26        0.230769
59378               1              E1              26        0.076923
59379               1              D2              10        0.230769
59380               1              A8              26        0.076923

       Product_Info_5  Product_Info_6  Product_Info_7  Response        Wt
0                   2               3               1       NaN  0.338912
1                   2               3               1       NaN  0.311715
2                   2               3               1       NaN  0.320084
3                   2               1               1       NaN  0.267782
4                   2               3               1       NaN  0.246862
5                   2               3               1       NaN  0.299163
6                   2               3               1       NaN  0.225941
7                   2               3               1       NaN  0.215481
8                   2               3               1       NaN  0.225941
9                   2               3               1       NaN  0.320084
10                  2               3               1       NaN  0.257322
11                  2               3               1       NaN  0.200837
12                  2               3               1       NaN  0.246862
13                  2               3               1       NaN  0.158996
14                  2               3               1       NaN  0.271967
15                  2               3               1       NaN  0.341004
16                  2               1               1       NaN  0.177824
17                  2               1               1       NaN  0.271967
18                  2               1               1       NaN  0.184100
19                  2               3               1       NaN  0.246862
20                  2               3               1       NaN  0.240586
21                  2               3               3       NaN  0.292887
22                  2               1               1       NaN  0.271967
23                  2               1               1       NaN  0.200837
24                  2               3               3       NaN  0.309623
25                  2               3               1       NaN  0.351464
26                  2               3               1       NaN  0.163180
27                  2               3               1       NaN  0.215481
28                  2               1               1       NaN  0.518828

In [11]:
df.head()

,BMI,Employment_Info_1,Employment_Info_2,Employment_Info_3,Employment_Info_4,Employment_Info_5,Employment_Info_6,Family_Hist_1,Family_Hist_2,Family_Hist_3,...,Medical_Keyword_9,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Response,Wt
0,0.472262,0.150,3,1,0.00,2,0.50,3,NaN,0.627451,...,0,1,D3,26,0.487179,2,3,1,NaN,0.338912
1,0.484984,0.000,1,3,0.07,2,0.20,2,NaN,0.529412,...,0,1,A2,26,0.076923,2,3,1,NaN,0.311715
2,0.519103,0.143,9,1,0.00,2,0.45,3,0.666667,NaN,...,0,1,D3,26,0.144667,2,3,1,NaN,0.320084
3,0.486962,0.210,9,1,0.00,2,1.00,2,NaN,0.686275,...,0,1,A1,26,0.151709,2,1,1,NaN,0.267782
4,0.428718,0.085,9,1,0.00,2,0.20,2,0.449275,NaN,...,0,1,A1,26,0.076923,2,3,1,NaN,0.246862

In [13]:
df.dtypes

BMI                    float64
Employment_Info_1      float64
Employment_Info_2        int64
Employment_Info_3        int64
Employment_Info_4      float64
Employment_Info_5        int64
Employment_Info_6      float64
Family_Hist_1            int64
Family_Hist_2          float64
Family_Hist_3          float64
Family_Hist_4          float64
Family_Hist_5          float64
Ht                     float64
Id                       int64
Ins_Age                float64
Insurance_History_1      int64
Insurance_History_2      int64
Insurance_History_3      int64
Insurance_History_4      int64
Insurance_History_5    float64
Insurance_History_7      int64
Insurance_History_8      int64
Insurance_History_9      int64
InsuredInfo_1            int64
InsuredInfo_2            int64
InsuredInfo_3            int64
InsuredInfo_4            int64
InsuredInfo_5            int64
InsuredInfo_6            int64
InsuredInfo_7            int64
                        ...
Medical_Keyword_34       int64
Medical_Keyword_35       int64
Medical_Keyword_36       int64
Medical_Keyword_37       int64
Medical_Keyword_38       int64
Medical_Keyword_39       int64
Medical_Keyword_4        int64
Medical_Keyword_40       int64
Medical_Keyword_41       int64
Medical_Keyword_42       int64
Medical_Keyword_43       int64
Medical_Keyword_44       int64
Medical_Keyword_45       int64
Medical_Keyword_46       int64
Medical_Keyword_47       int64
Medical_Keyword_48       int64
Medical_Keyword_5        int64
Medical_Keyword_6        int64
Medical_Keyword_7        int64
Medical_Keyword_8        int64
Medical_Keyword_9        int64
Product_Info_1           int64
Product_Info_2          object
Product_Info_3           int64
Product_Info_4         float64
Product_Info_5           int64
Product_Info_6           int64
Product_Info_7           int64
Response               float64
Wt                     float64
dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 79146 entries, 0 to 59380
Columns: 128 entries, BMI to Wt
dtypes: float64(19), int64(108), object(1)
memory usage: 77.9+ MB

In [15]:
df.describe()

,BMI,Employment_Info_1,Employment_Info_2,Employment_Info_3,Employment_Info_4,Employment_Info_5,Employment_Info_6,Family_Hist_1,Family_Hist_2,Family_Hist_3,...,Medical_Keyword_8,Medical_Keyword_9,Product_Info_1,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Response,Wt
count,79146.000000,79124.000000,79146.000000,79146.000000,70230.000000,79146.000000,64505.000000,79146.000000,40610.000000,33841.000000,...,79146.000000,79146.000000,79146.000000,79146.000000,79146.000000,79146.000000,79146.000000,79146.000000,59381.000000,79146.000000
mean,0.469773,0.077930,8.592323,1.307053,0.006340,2.144480,0.363228,2.686605,0.474554,0.498315,...,0.010373,0.006886,1.026015,24.392199,0.327810,2.006848,2.669143,1.043540,5.636837,0.292580
std,0.122517,0.082746,4.218494,0.720993,0.033368,0.351578,0.350589,0.482933,0.154993,0.140164,...,0.101320,0.082696,0.159181,5.101213,0.281791,0.082470,0.743138,0.291821,2.456833,0.089365
min,0.000000,0.000000,1.000000,1.000000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,2.000000,1.000000,1.000000,1.000000,0.000000
25%,0.385344,0.035000,9.000000,1.000000,0.000000,2.000000,0.060000,2.000000,0.362319,0.411765,...,0.000000,0.000000,1.000000,26.000000,0.076923,2.000000,3.000000,1.000000,4.000000,0.225941
50%,0.452515,0.060000,9.000000,1.000000,0.000000,2.000000,0.250000,3.000000,0.463768,0.519608,...,0.000000,0.000000,1.000000,26.000000,0.230769,2.000000,3.000000,1.000000,6.000000,0.288703
75%,0.533653,0.100000,9.000000,1.000000,0.000000,2.000000,0.580000,3.000000,0.579710,0.607843,...,0.000000,0.000000,1.000000,26.000000,0.487179,2.000000,3.000000,1.000000,8.000000,0.345188
max,1.000000,1.000000,38.000000,3.000000,1.000000,3.000000,1.000000,3.000000,1.000000,1.000000,...,1.000000,1.000000,2.000000,38.000000,1.000000,3.000000,3.000000,3.000000,8.000000,1.000000

In [20]:
df[['BMI', 'Ht', 'Wt', 'Ins_Age']]

            BMI        Ht        Wt   Ins_Age
0      0.472262  0.781818  0.338912  0.611940
1      0.484984  0.727273  0.311715  0.626866
2      0.519103  0.709091  0.320084  0.582090
3      0.486962  0.654545  0.267782  0.522388
4      0.428718  0.672727  0.246862  0.298507
5      0.379754  0.818182  0.299163  0.567164
6      0.373628  0.690909  0.225941  0.298507
7      0.388655  0.654545  0.215481  0.059701
8      0.446361  0.618182  0.225941  0.611940
9      0.443418  0.781818  0.320084  0.328358
10     0.362274  0.763636  0.257322  0.313433
11     0.314304  0.709091  0.200837  0.656716
12     0.393349  0.709091  0.246862  0.194030
13     0.297097  0.636364  0.158996  0.253731
14     0.401656  0.745455  0.271967  0.179104
15     0.408129  0.854545  0.341004  0.462687
16     0.367372  0.600000  0.177824  0.582090
17     0.385344  0.763636  0.271967  0.194030
18     0.345771  0.636364  0.184100  0.208955
19     0.488220  0.618182  0.246862  0.656716
20     0.455286  0.636364  0.240586  0.373134
21     0.418301  0.763636  0.292887  0.119403
22     0.354708  0.800000  0.271967  0.328358
23     0.344810  0.672727  0.200837  0.313433
24     0.444667  0.763636  0.309623  0.507463
25     0.551286  0.727273  0.351464  0.522388
26     0.391202  0.545455  0.163180  0.567164
27     0.339455  0.709091  0.215481  0.432836
28     0.631095  0.872727  0.518828  0.656716
29     0.325490  0.636364  0.173640  0.059701
...         ...       ...       ...       ...
59351  0.491491  0.781818  0.351464  0.134328
59352  0.488220  0.618182  0.246862  0.358209
59353  0.539563  0.781818  0.382845  0.179104
59354  0.494104  0.763636  0.341004  0.402985
59355  0.547451  0.745455  0.361925  0.223881
59356  0.618050  0.600000  0.299163  0.522388
59357  0.491491  0.781818  0.351464  0.582090
59358  0.586182  0.727273  0.372385  0.238806
59359  0.603660  0.781818  0.424686  0.447761
59360  0.258890  0.654545  0.146444  0.194030
59361  0.411703  0.727273  0.267782  0.268657
59362  0.491491  0.781818  0.351464  0.253731
59363  0.464570  0.563636  0.205021  0.746269
59364  0.261651  0.727273  0.177824  0.552239
59365  0.458023  0.709091  0.284519  0.641791
59366  0.443418  0.781818  0.320084  0.582090
59367  0.661270  0.600000  0.320084  0.373134
59368  0.464047  0.727273  0.299163  0.417910
59369  0.693246  0.745455  0.451883  0.611940
59370  0.477625  0.763636  0.330544  0.238806
59371  0.558626  0.709091  0.343096  0.537313
59372  0.438076  0.763636  0.305439  0.477612
59373  0.332885  0.800000  0.257322  0.208955
59374  0.484658  0.690909  0.288703  0.164179
59375  0.494827  0.654545  0.271967  0.477612
59376  0.519103  0.709091  0.320084  0.074627
59377  0.551119  0.800000  0.403766  0.432836
59378  0.360969  0.745455  0.246862  0.104478
59379  0.462452  0.690909  0.276151  0.507463
59380  0.539563  0.781818  0.382845  0.447761

[79146 rows x 4 columns]

In [ ]:
import pylab as P
df['BMI'].hist()
P.show()

In [ ]:
import pylab as P
df['Ht'].hist()
P.show()